name: "Update datasets on PR build"
on: pull_request

jobs:
  download:
    runs-on: windows-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install Python dependencies
        run: |
          pipenv install
      - name: Update data
        run: |
          pipenv run python generate_data.py
