name: "Update datasets"
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install Python dependencies
        run: |
          pipenv install
      - name: Run unit tests
        run: |
          pipenv run python -m unittest
      - name: Update data
        run: |
          pipenv run python generate_data.py
      - name: Commit files
        run: |
          git config --local user.email "tryggvigy@gmail.com"
          git config --local user.name "tryggvigy Action"
          git add .
          git commit -m "Update data"
        continue-on-error: true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
